//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.14 at 10:41:45 PM IST 
//


package com.skill.tracker.api.jaxb.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for skillTrackerRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skillTrackerRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skillTracker" type="{http://skill-tracker.com/skill-tracker-api-models}SkillTrackerType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skillTrackerRequest", namespace = "http://skill-tracker.com/skill-tracker-api", propOrder = {
    "skillTracker"
})
@XmlRootElement(name = "SkillTrackerRequest", namespace = "http://skill-tracker.com/skill-tracker-api")
public class SkillTrackerRequest {

    protected SkillTrackerType skillTracker;

    /**
     * Gets the value of the skillTracker property.
     * 
     * @return
     *     possible object is
     *     {@link SkillTrackerType }
     *     
     */
    public SkillTrackerType getSkillTracker() {
        return skillTracker;
    }

    /**
     * Sets the value of the skillTracker property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillTrackerType }
     *     
     */
    public void setSkillTracker(SkillTrackerType value) {
        this.skillTracker = value;
    }

}
