//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.14 at 10:41:45 PM IST 
//


package com.skill.tracker.api.jaxb.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for skillTrackerResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skillTrackerResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skillTrackers" type="{http://skill-tracker.com/skill-tracker-api-models}SkillTrackerType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://skill-tracker.com/skill-tracker-api-common}response"/&gt;
 *         &lt;element ref="{http://skill-tracker.com/skill-tracker-api-common}pageable"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skillTrackerResponse", namespace = "http://skill-tracker.com/skill-tracker-api", propOrder = {
    "skillTrackers",
    "response",
    "pageable"
})
@XmlRootElement(name = "SkillTrackerResponse", namespace = "http://skill-tracker.com/skill-tracker-api")
public class SkillTrackerResponse {

    protected List<SkillTrackerType> skillTrackers;
    @XmlElement(namespace = "http://skill-tracker.com/skill-tracker-api-common", required = true)
    protected Response response;
    @XmlElement(namespace = "http://skill-tracker.com/skill-tracker-api-common", required = true)
    protected Pageable pageable;

    /**
     * Gets the value of the skillTrackers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skillTrackers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkillTrackers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkillTrackerType }
     * 
     * 
     */
    public List<SkillTrackerType> getSkillTrackers() {
        if (skillTrackers == null) {
            skillTrackers = new ArrayList<SkillTrackerType>();
        }
        return this.skillTrackers;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the pageable property.
     * 
     * @return
     *     possible object is
     *     {@link Pageable }
     *     
     */
    public Pageable getPageable() {
        return pageable;
    }

    /**
     * Sets the value of the pageable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pageable }
     *     
     */
    public void setPageable(Pageable value) {
        this.pageable = value;
    }

}
